# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.
# -*- mode: yaml -*-

# jobs:
#   - template: ./.azure-pipelines/azure-pipelines-linux.yml
#   - template: ./.azure-pipelines/azure-pipelines-win.yml
#   - template: ./.azure-pipelines/azure-pipelines-osx.yml

pool:
  vmImage: "ubuntu-latest"


jobs:
- job: Test
  steps:
  - script: |
      sudo timedatectl set-timezone "America/New_York"
      echo "I ran at $(date)"
    displayName: Report date and time
