# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.
# -*- mode: yaml -*-

# jobs:
#   - template: ./.azure-pipelines/azure-pipelines-linux.yml
#   - template: ./.azure-pipelines/azure-pipelines-win.yml
#   - template: ./.azure-pipelines/azure-pipelines-osx.yml

# schedules:
# - cron: "*/1 * * * *"
#   displayName: Run on a schedule
#   branches:
#     include:
#     - nightlies-azure
#   always: true

pool:
  vmImage: "ubuntu-latest"


jobs:
- job: Test
  steps:
  - script: |
      sudo timedatectl set-timezone "America/New_York"
      echo "date: $(date)"
    displayName: Report date and time
  - script: |
      git checkout main
      git checkout -B nightly-build main
      version_current=$(curl -sL https://raw.githubusercontent.com/TileDB-Inc/TileDB/dev/tiledb/sm/c_api/tiledb_version.h | grep '#define' | cut -d' ' -f3 | tr '\n' '.')
      version="${version_current}$(date +%Y_%m_%d)"
      sed -i \
        s/"{% set version = \".*\" %}"/"{% set version = \"$version\" %}"/ \
        recipe/meta.yaml
      git diff
      # Push update to GitHub
      git config --get user.name
      git config --get user.email
      git config --list
      git config --local user.name "Azure Pipelines"
      git add recipe/meta.yaml
      git commit --allow-empty -m "Nightly build for $version"
      # git push origin nightly-build
    displayName: Bump nightly version
