# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.
# -*- mode: yaml -*-

# jobs:
#   - template: ./.azure-pipelines/azure-pipelines-linux.yml
#   - template: ./.azure-pipelines/azure-pipelines-win.yml
#   - template: ./.azure-pipelines/azure-pipelines-osx.yml

# schedules:
# - cron: "*/1 * * * *"
#   displayName: Run on a schedule
#   branches:
#     include:
#     - nightlies-azure
#   always: true

pool:
  vmImage: "ubuntu-latest"


jobs:
- job: Test
  steps:
  - script: |
      sudo timedatectl set-timezone "America/New_York"
      echo "date: $(date)"
    displayName: Report date and time
  - script: |
      git checkout main
      git checkout -B nightly-build main

      # Bump version
      version_current=$(curl -sL https://raw.githubusercontent.com/TileDB-Inc/TileDB/dev/tiledb/sm/c_api/tiledb_version.h | grep '#define' | cut -d' ' -f3 | tr '\n' '.')
      version="${version_current}$(date +%Y_%m_%d)"
      sed -i \
        s/"{% set version = \".*\" %}"/"{% set version = \"$version\" %}"/ \
        recipe/meta.yaml

      # Disable conda-forge validation
      echo "conda_forge_output_validation: False" >> conda-forge.yml

      # Change upload channel
      echo -e "channel_targets:\n  - jdblischak nightlies" >> recipe/conda_build_config.yaml

      git diff

      # Push to GitHub
      git config --local user.name "Azure Pipelines"
      git config --local user.email "azure@microsoft.com" # fake, but consistent email
      git add conda-forge.yml recipe/conda_build_config.yaml recipe/meta.yaml
      git commit -m "Nightly build for $version"
      git remote -v
      gh auth login --git-protocol HTTPS
      gh auth status
      git push https://jdblischak@github.com/jdblischak/tiledb-feedstock.git nightly-build
    displayName: Bump nightly version
    env:
      GITHUB_TOKEN: $(GITHUB_PAT)
