# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.
# -*- mode: yaml -*-

stages:
- stage: linux
  jobs:
  - template: ./.azure-pipelines/azure-pipelines-linux.yml

- stage: win
  jobs:
  - template: ./.azure-pipelines/azure-pipelines-win.yml

- stage: osx
  jobs:
  - template: ./.azure-pipelines/azure-pipelines-osx.yml
