# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.
# -*- mode: yaml -*-

jobs:
  - job: top-level-linux
    steps:
    - template: ./.azure-pipelines/azure-pipelines-linux.yml
  - job: top-level-win
    dependsOn: [top-level-linux]
    steps:
    - template: ./.azure-pipelines/azure-pipelines-win.yml
  - job: top-level-osx
    dependsOn: [top-level-win]
    steps:
    - template: ./.azure-pipelines/azure-pipelines-osx.yml