# I manually edited this file to try and get around Azure parallelism
# restrictions
pool:
  vmImage: ubuntu-latest
steps:
- script: |
       rm -rf /opt/ghc
       df -h
  displayName: Manage disk space
- script: |
      export CONFIG=linux_64_
      export UPLOAD_PACKAGES=True
      export DOCKER_IMAGE="quay.io/condaforge/linux-anvil-cos7-x86_64"
      export CI=azure
      export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
      export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
      if [[ "${BUILD_REASON:-}" == "PullRequest" ]]; then
        export IS_PR_BUILD="True"
      else
        export IS_PR_BUILD="False"
      fi
      .scripts/run_docker_build.sh
  displayName: Run docker build
  env:
    BINSTAR_TOKEN: $(BINSTAR_TOKEN)
